version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      # 11 am PST
      time: "11:00"
      # PST timezone
      timezone: "America/Los_Angeles"
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with "chore"
      # include a list of updated dependencies
      prefix: "chore:"
      include: "scope"
    reviewers:
      - "emostov"
      - "TarikGul"
    allow: 
      - dependency-name: "@polkadot/api"
      - dependency-name: "@polkadot/apps-config"
      - dependency-name: "@polkadot/util-crypto"
    labels:
      - "dependencies"
